{% set name = "pyplume" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  entry_points:
    - pyplume.mech=pyplume.mech:mechCLI
    - pyplume.model=pyplume.model:modelCLI
    - pyplume.figures=pyplume.figures:figuresCLI
    - pyplume.statistics=pyplume.statistics:statisticsCLI
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cantera
    - h5py
    - matplotlib
    - pip
    - pytest
    - python
  run:
    - cantera
    - h5py
    - matplotlib
    - pytest
    - python

test:
  imports:
    - pyplume
  commands:
    - pyplume.mech --help
    - pyplume.model --help
    - pyplume.figures --help
    - pyplume.statistics --help

about:
  home: "https://github.com/SoftwareDevEngResearch/plume-generation-and-analysis"
  license: BSD
  license_family: BSD
  summary: "This package contains files to build models for exhaust plume analysis and methods to analyze the results."
  doc_url: "https://pypi.org/project/pyplume/"
  dev_url: "https://github.com/SoftwareDevEngResearch/pyplume"
  description: "PyPlume is a package that relies primarily on Cantera to simulate exhaust plume networks and analyze the resulting data. It has a few different
  models currently implemented."
extra:
  recipe-maintainers:
    - anthony-walker
