{% set name = "pyplume" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 421e56272058007ed97623b9d655718c1f009084557274674a5699554970ad9a
  # git_url: https://github.com/SoftwareDevEngResearch/pyplume.git
  # git_rev: 1.1.4
  # git_depth: 1 # (Defaults to -1/not shallow)
build:
  number: 0
  entry_points:
    - pyplume.mech=pyplume.mech:mechCLI
    - pyplume.model=pyplume.model:modelCLI
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cantera
    - h5py
    - pip
    - pytest
    - python
  run:
    - cantera
    - h5py
    - pytest
    - python

test:
  imports:
    - pyplume
    - pyplume.tests
    - pyplume.model
    - pyplume.mech
    - pyplume.output
    - pyplume.figs
    - pyplume.stats
  commands:
    - pyplume.mech --help
    - pyplume.model --help

about:
  home: "https://github.com/SoftwareDevEngResearch/plume-generation-and-analysis"
  license: BSD
  license_family: BSD
  summary: "This package contains files to build models for exhaust plume analysis and methods to analyze the results."
  doc_url: "https://pypi.org/project/pyplume/"
  dev_url: "https://github.com/SoftwareDevEngResearch/pyplume"

extra:
  recipe-maintainers:
    - anthony-walker
